 
/************************************************************************
 * FileName  DataTable\DataTableContextInfrastructure.IAg
 * FileDesc data/context
 * Author   System
 * CreateTime 2018-08-29 17:44:04

 * Copyright (c) Socool 2017. All Rights Reserved. 
 * ***********************************************************************/

// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5

using Microsoft.EntityFrameworkCore.Metadata.Builders;

#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning
namespace Titan.Model.DataModel
{
    using System;
    using System.Linq;
    using Titan.Model;
    using Microsoft.EntityFrameworkCore;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations.Schema;

	#region POCO classes

    // SysCompany
    ///<summary>
    /// 服务器大区
    ///</summary>
    [Table("Author")]
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.30.0.0")]
    public class Author : IAggregateRoot
    {
        public int Id { get; set; }
        //作者姓名
        public string AuthorName { get; set; }
    }
	#endregion

	#region POCO Configuration
    // SysTitle
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.30.0.0")]
    public class SysTitleConfiguration : IEntityTypeConfiguration<Author>
    {
        public void Configure(EntityTypeBuilder<Author> builder)
        {
            builder.ToTable("Author").HasKey(r => r.Id); //注：如果Author这个表是以Id做主键的，则可以不用写HasKey(r=>r.Id);
            builder.Property(r => r.AuthorName).HasMaxLength(20);
        }
    }

	#endregion
}
// </auto-generated>
